jobs:
  label:
    permissions:
      issues: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: damccorm/tag-ur-it@6fa72bbf1a2ea157b533d7e7abeafdb5855dbea5
      with:
        configuration-path: ./.github/issue-rules.yml
        repo-token: ${{ secrets.GITHUB_TOKEN }}
name: IssueTagger
on:
  repository_dispatch:
    types: trigger-ga___issue_tagger.yml
